#!/usr/bin/env python3

import os
import sys
import yaml


def main(src_yaml_path: str, tar_dir: str) -> None:
    """
bool check_edge(GraphEdge edge, Flags flags) {
    switch (edge) {
        case GraphEdge::XXX:
            return {{ edge.check }};
    }
}

int execute_edge(GraphEdge edge, Game game, Player player, {{ something else? }}) {
    switch (edge) {
        case GraphEdge::XXX:
            return {{ edge.execute }};
    }
}
"""


if __name__ == "__main__":

    src_yaml_path = os.path.join(
        os.path.dirname(__file__), "..", "static", "game-graph.yml"
    )
    tar_dir = os.path.join(os.path.dirname(__file__), "..", "include", "generated")

    main(src_yaml_path, tar_dir)
